### ISSUE TITLE
Packaging kernel?

### ISSUE THREAD

**Issue by alejandroandreu** [jetsonhacks/buildJetsonTX2Kernel#12]
I've generated my own kernel, enabling and compiling all the modules I need for my day-to-day operations. If I were to package the kernel (so setting up a board doesn't take that long), do you know which files should I put in?

I'm just asking since the root filesystem of the TX2 is kind of special :smile:

**Comment by jetsonhacks** [comment]
Most people clone the entire disk image, and save it to their PC. Typically they configure the Jetson so that all of their application(s) are installed before saving the disk image. That way, during development when things (inevitably) go south, they can restore to a known working point without having to rebuild everything.

Note that you should also have manual build instructions (or scripts) so that you can rebuild everything from scratch.

**Comment by xoxota99** [comment]
Can you recommend a link with step-by-step instructions on how to clone, export/save, and restore a rootfs image? (Linux / Jetson noob here).

**Comment by jetsonhacks** [comment]
https://elinux.org/Jetson/TX2_Cloning

**Comment by xoxota99** [comment]
Perfect! (And timely, since my TX2 eMMC just got corrupted, so I have to reimage it now. sigh.)

**Comment by alejandroandreu** [comment]
https://cyclicredundancy.wordpress.com/2014/05/10/flashing-the-rootfs-on-a-nvidia-jetson-tk1/ this applies to TX2 as well, maybe it's helpful to you too

**Comment by alejandroandreu** [comment]
Thanks @jetsonhacks . So basically back up all in /boot partition and package that up?
