### ISSUE TITLE
How to copy image to eMMC?

### ISSUE THREAD

**Issue by dan9thsense** [jetsonhacks/buildJetsonTX2Kernel#17]
The end of the instructions say to "copy the Image file over to the eMMC in the eMMC's /boot directory."  How do you do that?  Do you have to flash the TX2?

Is that needed when using the TX2 development kit?

**Comment by jetsonhacks** [comment]
If you have created the Image file on external media, the Image file is in the <media>/boot directory
The Jetson typically boots from the eMMC, so it would not see the new Image file. Therefore, you would cp the <media>/boot/Image file to the <eMMC>/boot/Image using sudo. 
See the copyImage script as an example. I do not know how to refer easily to the internal eMMC for use in a script, or else I would have added it.

**Comment by dan9thsense** [comment]
Sorry, I guess I am a bit dense.  I flashed the TX2 development kit, then created the file and it is located in /boot.  Properties show a disk size of 29.5 GB, so perhaps this is the eMMC (32GB) after all.  I thought perhaps there was an external drive as part of the development kit.

What is the difference between flashing the TX2 vs. creating the kernel from source and installing in /boot?

**Comment by jetsonhacks** [comment]
Here's an article on the kernel build process: https://www.jetsonhacks.com/2018/03/22/build-kernel-modules-nvidia-jetson-tx2-2/

The eMMC is internal flash memory. External memory can be added using a SD card, a USB drive, SATA drive or PCIE drive. In a variety of flavors, SSD, disk, and so on. Developers may want to develop on an external drive for a couple of reasons. First, there is a lot more room available and second the drives are much faster than the internal flash memory. 

If you were to build the Image on external memory/media (this is required on the Jetson TX1 which does not have enough internal eMMC flash memory to hold both the kernel sources and build artifacts), you need to copy the Image from external memory to the internal flash/eMMC so that it can boot from the new Image. Typically you would have both the new kernel Image and the old kernel Image available with the appropriate entries in extlinux.conf so that you can boot into the old/new image using a serial console. This is useful if there is a bad kernel build.

Flashing the TX2 builds a new file system (a complete System Image) and flashes it onto the Jetson. The Image that is created in this process is a subset, and refers specifically to the Linux kernel image, built in drivers, and device drivers. 

In addition, flashing also creates 14 other hidden partitions on the internal eMMC that hold such things as the device tree.

**Comment by dan9thsense** [comment]
Thank you very much for your help on this.  That link is the one I used to build the kernel.  I didn't understand the difference between flashing the drive vs. just creating and install a kernel image.  Your detailed answer makes it clear.
