### ISSUE TITLE
wlan device not found

### ISSUE THREAD

**Issue by agaviria** [jetsonhacks/buildJetsonTX2Kernel#4]
I managed to build the TX2 kernel onto SSD but I'm unable to get any WIFI network detection:

    $ iwconfig
    lo    no wireless extensions.
    dummy0    no wireless extensions.
    tunl0     no wireless extensions.
    eth0    no wireless extensions.

    $ sudo ifconfig wlan0 up
    [sudo] password for nvidia:
    wlan0: ERROR while getting interface flags: No such device

    $ sudo ifconfig wlan0 scan
    command failed: No such device (-19)

Any suggestions on how to get this working?

**Comment by jetsonhacks** [comment]
No suggestions. Did your system work with WiFi before building the kernel? If you switch back to the older kernel and boot from eMMC, does it work correctly? I can't tell from your description which version of L4T you are running. If you built your kernel on the SSD, did you copy the image file back to the eMMC? Did you set up your extlinux.conf file to correctly point at the SSD root? 
You don't mention where you got the original config.gz file, was it from a running system? Did you modify the scripts to take into account that you were building on the SSD instead of the eMMC?

I assume that you have answered all those questions on your side, my guess is that you will have to build a kernel on your linux host machine to have it work correctly.

**Comment by jetsonhacks** [comment]
No answer to request for information. Closing.
